services:
  backend:
    image: backend-dev:latest
    container_name: backend-dev
    ports: 
      - 3000:3000
  
  frontend:
    image: frontend-dev:latest
    container_name: frontend-dev
    ports: 
      - 5173:5173
